name: 'Run ConneKt Scripts'
description: 'Run a list of scripts inside a container with environment setup'

inputs:
  files:
    description: 'List of full paths to scripts to execute (newline separated)'
    required: true
  env_file:
    description: 'Path to env file (connekt.env.json)'
    required: true
  env:
    description: 'Environment name'
    required: true
  image:
    description: 'Docker image to use'
    required: false
    default: 'ghcr.io/amplicode/connekt:0.1'

runs:
  using: 'composite'
  steps:
    - name: Run Scripts Inside Docker
      run: |
        echo "${{ inputs.files }}" | while read filepath; do
          if [ -n "$filepath" ]; then
            filename=$(basename "$filepath")
            dirpath=$(dirname "$filepath")

            echo "Running $filename from $dirpath..."

            docker run --rm \
              --add-host=host.docker.internal:host-gateway \
              -v "$dirpath":/connekt/scripts \
              -v ${{ inputs.env_file }}:/connekt/scripts/connekt.env.json \
              ${{ inputs.image }} \
              --env-name=${{ inputs.env }} \
              --env-file=scripts/connekt.env.json \
              --script=scripts/"$filename"
          fi
        done
      shell: bash
