name: 'Run ConneKt Scripts'
description: 'Run a list of scripts inside a container with environment setup'

inputs:
  files:
    description: 'List of full paths to scripts to execute (newline separated)'
    required: true
  env_file:
    description: 'Path to env file (connekt.env.json)'
    required: false
  env:
    description: 'Environment name'
    required: false
  env_params:
    description: 'List of env-param values (newline separated key=value)'
    required: false
    default: ''
  image:
    description: 'Docker image to use'
    required: false
    default: 'ghcr.io/amplicode/connekt:0.1'

runs:
  using: 'composite'
  steps:
    - name: Run Scripts Inside Docker
      run: |
        ENV_PARAM_ARGS=""
        if [ -n "${{ inputs.env_params }}" ]; then
          while read param; do
            if [ -n "$param" ]; then
              ENV_PARAM_ARGS="$ENV_PARAM_ARGS --env-param $param"
            fi
          done <<< "${{ inputs.env_params }}"
        fi

        ENV_NAME_ARG=""
        if [ -n "${{ inputs.env }}" ]; then
          ENV_NAME_ARG="--env-name=${{ inputs.env }}"
        fi

        ENV_FILE_MOUNT=""
        ENV_FILE_ARG=""
        if [ -n "${{ inputs.env_file }}" ]; then
          ENV_FILE_ABS_PATH="$(realpath ${{ inputs.env_file }})"
          ENV_FILE_MOUNT="-v $ENV_FILE_ABS_PATH:/connekt/scripts/connekt.env.json"
          ENV_FILE_ARG="--env-file=scripts/connekt.env.json"
        fi

        echo "${{ inputs.files }}" | while read filepath; do
          if [ -n "$filepath" ]; then
            filename=$(basename "$filepath")
            dirpath=$(dirname "$filepath")

            echo "Running $filename from $dirpath..."

            docker run --rm \
              --add-host=host.docker.internal:host-gateway \
              -v "$dirpath":/connekt/scripts \
              $ENV_FILE_MOUNT \
              ${{ inputs.image }} \
              $ENV_NAME_ARG \
              $ENV_FILE_ARG \
              --script=scripts/"$filename" \
              $ENV_PARAM_ARGS
          fi
        done
      shell: bash
